version: "3.8"
services:
    api:
        # image: thomas-oliver/nestjs-dockerized 
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            DATABASE_URL: postgresql://postgres:mnmthetopdawg@localhost:5432/yadb?schema=public
            NODE_ENV: development
            PORT: 3000
        ports:
            - "3000:3000"

    postgres:
        image: postgres:16.0
        container_name: postgres
        restart: always
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mnmthetopdawg
            POSTGRES_DB: yadb