-- AlterTable
ALTER TABLE "EmployeesCheck" ALTER COLUMN "comment" DROP NOT NULL,
ALTER COLUMN "comment" SET DEFAULT '',
ALTER COLUMN "checkIn" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "checkOut" DROP NOT NULL,
ALTER COLUMN "checkOut" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "presenceDuration" DROP NOT NULL,
ALTER COLUMN "presenceDuration" SET DEFAULT CURRENT_TIMESTAMP;
